Update to terraform v1.0.0
serlo/infrastructure-modules-kpi pull request #6
Opened 2021-06-16 21:06 UTC by kulla

2021-06-16 21:07 UTC, inyono requested changes

2021-06-16 21:07 UTC, inyono commented on .github/workflows/terraform.yml
> +          terraform_version: ~1.0.0
Should be switched from ~ to ^ now.

2021-06-16 21:07 UTC, inyono commented on .github/workflows/terraform.yml
> +          terraform_version: ~1.0.0
Same here

2021-06-17 08:21 UTC, kulla commented
@inyono done

2021-06-17 10:31 UTC, inyono approved these changes

2021-06-17 10:31 UTC, merged